name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-build:
    runs-on: ubuntu-latest
    needs: run-lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm install
      - name: Display environment variables
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ROLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ROLE_KEY }}
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}"
          echo "NEXT_PUBLIC_SUPABASE_ROLE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ROLE_KEY }}"
      - name: Try to build
        run: npm run build